In [1]:
!pip install pandas mlxtend

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: mlxtend in /usr/local/lib/python3.12/dist-packages (0.23.4)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.16.2)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.6.1)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (3.10.0)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.5.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (4.60.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.2.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)

In [2]:
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules
from google.colab import files

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [3]:
# Upload file
uploaded = files.upload()

# Load the uploaded CSV
df = pd.read_csv(list(uploaded.keys())[0])
df.head()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

Saving Groceries_dataset.csv to Groceries_dataset.csv

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

   Member_number        Date   itemDescription
0           1808  21-07-2015    tropical fruit
1           2552  05-01-2015        whole milk
2           2300  19-09-2015         pip fruit
3           1187  12-12-2015  other vegetables
4           3037  01-02-2015        whole milk

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [4]:
print(df.info())
print(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38765 entries, 0 to 38764
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Member_number    38765 non-null  int64
 1   Date             38765 non-null  object
 2   itemDescription  38765 non-null  object
dtypes: int64(1), object(2)
memory usage: 908.7+ KB
None
   Member_number        Date   itemDescription
0           1808  21-07-2015    tropical fruit
1           2552  05-01-2015        whole milk
2           2300  19-09-2015         pip fruit
3           1187  12-12-2015  other vegetables
4           3037  01-02-2015        whole milk

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [15]:
# Group items by Member_number and create a list of items per transaction
transactions = df.groupby('Member_number')['itemDescription'].apply(list).tolist()

# Check first 5 transactions
transactions[:5]

[['soda',
  'canned beer',
  'sausage',
  'sausage',
  'whole milk',
  'whole milk',
  'pickled vegetables',
  'misc. beverages',
  'semi-finished bread',
  'hygiene articles',
  'yogurt',
  'pastry',
  'salty snack'],
 ['frankfurter',
  'frankfurter',
  'beef',
  'sausage',
  'whole milk',
  'soda',
  'curd',
  'white bread',
  'whole milk',
  'soda',
  'whipped/sour cream',
  'rolls/buns'],
 ['tropical fruit',
  'butter milk',
  'butter',
  'frozen vegetables',
  'sugar',
  'specialty chocolate',
  'whole milk',
  'other vegetables'],
 ['sausage',
  'root vegetables',
  'rolls/buns',
  'detergent',
  'frozen meals',
  'rolls/buns',
  'dental care',
  'rolls/buns'],
 ['other vegetables',
  'pip fruit',
  'root vegetables',
  'canned beer',
  'rolls/buns',
  'whole milk',
  'other vegetables',
  'hygiene articles',
  'whole milk',
  'whole milk',
  'frozen fish',
  'red/blush wine',
  'chocolate',
  'shopping bags',
  'dish cleaner',
  'packaged fruit/vegetables',
  'tropical fruit',
  'rolls/buns',
  'cling film/bags',
  'chocolate',
  'pastry']]

In [16]:
te = TransactionEncoder()
te_array = te.fit(transactions).transform(transactions)
basket_df = pd.DataFrame(te_array, columns=te.columns_)

# Preview the encoded dataframe
basket_df.head()

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,bags,baking powder,bathroom cleaner,beef,berries,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,False
1,False,False,False,False,False,False,False,False,True,False,...,False,False,False,True,False,True,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [17]:
frequent_itemsets = apriori(basket_df, min_support=0.05, use_colnames=True)
frequent_itemsets.sort_values(by='support', ascending=False, inplace=True)

# Show top 10 frequent itemsets
frequent_itemsets.head(10)

      support                        itemsets
55   0.458184                    (whole milk)
37   0.376603              (other vegetables)
41   0.349666                    (rolls/buns)
47   0.313494                          (soda)
56   0.282966                        (yogurt)
51   0.233710                (tropical fruit)
42   0.230631               (root vegetables)
5    0.213699                 (bottled water)
44   0.206003                       (sausage)
116  0.191380  (whole milk, other vegetables)

In [18]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.3)
rules = rules.sort_values(by='lift', ascending=False)

# Show top 10 rules
rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']].head(10)

,antecedents,consequents,support,confidence,lift
97,"(whole milk, bottled water)",(other vegetables),0.056183,0.500000,1.327657
54,"(whole milk, other vegetables)",(yogurt),0.071832,0.375335,1.326434
98,"(other vegetables, bottled water)",(whole milk),0.056183,0.598361,1.305941
75,"(whole milk, rolls/buns)",(yogurt),0.065931,0.369253,1.304939
55,"(yogurt, other vegetables)",(whole milk),0.071832,0.597015,1.303003
48,(sausage),(yogurt),0.075423,0.366127,1.293892
76,"(rolls/buns, yogurt)",(whole milk),0.065931,0.592166,1.292420
107,"(soda, whole milk)",(yogurt),0.054387,0.359932,1.271999
53,"(whole milk, yogurt)",(other vegetables),0.071832,0.477002,1.266589
119,"(rolls/buns, other vegetables)",(yogurt),0.052335,0.356643,1.260377

In [19]:
for _, row in rules.iterrows():
    print(f"Bundle: {list(row['antecedents'])} -> {list(row['consequents'])} | Confidence: {row['confidence']:.2f} | Lift: {row['lift']:.2f}")

Bundle: ['whole milk', 'bottled water'] -> ['other vegetables'] | Confidence: 0.50 | Lift: 1.33
Bundle: ['whole milk', 'other vegetables'] -> ['yogurt'] | Confidence: 0.38 | Lift: 1.33
Bundle: ['other vegetables', 'bottled water'] -> ['whole milk'] | Confidence: 0.60 | Lift: 1.31
Bundle: ['whole milk', 'rolls/buns'] -> ['yogurt'] | Confidence: 0.37 | Lift: 1.30
Bundle: ['yogurt', 'other vegetables'] -> ['whole milk'] | Confidence: 0.60 | Lift: 1.30
Bundle: ['sausage'] -> ['yogurt'] | Confidence: 0.37 | Lift: 1.29
Bundle: ['rolls/buns', 'yogurt'] -> ['whole milk'] | Confidence: 0.59 | Lift: 1.29
Bundle: ['soda', 'whole milk'] -> ['yogurt'] | Confidence: 0.36 | Lift: 1.27
Bundle: ['whole milk', 'yogurt'] -> ['other vegetables'] | Confidence: 0.48 | Lift: 1.27
Bundle: ['rolls/buns', 'other vegetables'] -> ['yogurt'] | Confidence: 0.36 | Lift: 1.26
Bundle: ['whole milk', 'yogurt'] -> ['rolls/buns'] | Confidence: 0.44 | Lift: 1.25
Bundle: ['rolls/buns', 'yogurt'] -> ['other vegetables'] | Confidence: 0.47 | Lift: 1.25
Bundle: ['whole milk', 'sausage'] -> ['other vegetables'] | Confidence: 0.47 | Lift: 1.25
Bundle: ['yogurt', 'other vegetables'] -> ['rolls/buns'] | Confidence: 0.43 | Lift: 1.24
Bundle: ['soda', 'whole milk'] -> ['rolls/buns'] | Confidence: 0.43 | Lift: 1.23
Bundle: ['fruit/vegetable juice'] -> ['rolls/buns'] | Confidence: 0.43 | Lift: 1.23
Bundle: ['whole milk', 'other vegetables'] -> ['rolls/buns'] | Confidence: 0.43 | Lift: 1.23
Bundle: ['shopping bags'] -> ['soda'] | Confidence: 0.38 | Lift: 1.23
Bundle: ['rolls/buns', 'other vegetables'] -> ['whole milk'] | Confidence: 0.56 | Lift: 1.22
Bundle: ['whole milk', 'rolls/buns'] -> ['other vegetables'] | Confidence: 0.46 | Lift: 1.22
Bundle: ['soda', 'yogurt'] -> ['whole milk'] | Confidence: 0.56 | Lift: 1.22
Bundle: ['soda', 'other vegetables'] -> ['whole milk'] | Confidence: 0.56 | Lift: 1.22
Bundle: ['soda', 'whole milk'] -> ['other vegetables'] | Confidence: 0.46 | Lift: 1.22
Bundle: ['soda', 'other vegetables'] -> ['rolls/buns'] | Confidence: 0.42 | Lift: 1.21
Bundle: ['other vegetables', 'tropical fruit'] -> ['whole milk'] | Confidence: 0.55 | Lift: 1.21
Bundle: ['butter'] -> ['other vegetables'] | Confidence: 0.45 | Lift: 1.20
Bundle: ['sausage'] -> ['other vegetables'] | Confidence: 0.45 | Lift: 1.20
Bundle: ['sausage'] -> ['soda'] | Confidence: 0.37 | Lift: 1.20
Bundle: ['soda', 'rolls/buns'] -> ['whole milk'] | Confidence: 0.54 | Lift: 1.19
Bundle: ['shopping bags'] -> ['whole milk'] | Confidence: 0.54 | Lift: 1.18
Bundle: ['frankfurter'] -> ['soda'] | Confidence: 0.37 | Lift: 1.18
Bundle: ['curd'] -> ['rolls/buns'] | Confidence: 0.41 | Lift: 1.18
Bundle: ['sausage', 'other vegetables'] -> ['whole milk'] | Confidence: 0.54 | Lift: 1.18
Bundle: ['frankfurter'] -> ['other vegetables'] | Confidence: 0.44 | Lift: 1.18
Bundle: ['pip fruit'] -> ['yogurt'] | Confidence: 0.33 | Lift: 1.17
Bundle: ['bottled beer'] -> ['whole milk'] | Confidence: 0.54 | Lift: 1.17
Bundle: ['frozen vegetables'] -> ['whole milk'] | Confidence: 0.54 | Lift: 1.17
Bundle: ['beef'] -> ['whole milk'] | Confidence: 0.54 | Lift: 1.17
Bundle: ['newspapers'] -> ['rolls/buns'] | Confidence: 0.41 | Lift: 1.17
Bundle: ['shopping bags'] -> ['rolls/buns'] | Confidence: 0.41 | Lift: 1.17
Bundle: ['brown bread'] -> ['other vegetables'] | Confidence: 0.44 | Lift: 1.17
Bundle: ['bottled water'] -> ['other vegetables'] | Confidence: 0.44 | Lift: 1.17
Bundle: ['soda', 'rolls/buns'] -> ['other vegetables'] | Confidence: 0.44 | Lift: 1.17
Bundle: ['whole milk', 'rolls/buns'] -> ['soda'] | Confidence: 0.36 | Lift: 1.16
Bundle: ['whole milk'] -> ['yogurt'] | Confidence: 0.33 | Lift: 1.16
Bundle: ['yogurt'] -> ['whole milk'] | Confidence: 0.53 | Lift: 1.16
Bundle: ['canned beer'] -> ['rolls/buns'] | Confidence: 0.40 | Lift: 1.15
Bundle: ['whole milk', 'other vegetables'] -> ['soda'] | Confidence: 0.36 | Lift: 1.15
Bundle: ['pastry'] -> ['yogurt'] | Confidence: 0.33 | Lift: 1.15
Bundle: ['shopping bags'] -> ['other vegetables'] | Confidence: 0.43 | Lift: 1.15
Bundle: ['shopping bags'] -> ['yogurt'] | Confidence: 0.33 | Lift: 1.15
Bundle: ['canned beer'] -> ['whole milk'] | Confidence: 0.53 | Lift: 1.15
Bundle: ['domestic eggs'] -> ['whole milk'] | Confidence: 0.53 | Lift: 1.15
Bundle: ['whole milk', 'tropical fruit'] -> ['other vegetables'] | Confidence: 0.43 | Lift: 1.15
Bundle: ['whole milk', 'yogurt'] -> ['soda'] | Confidence: 0.36 | Lift: 1.15
Bundle: ['whipped/sour cream'] -> ['other vegetables'] | Confidence: 0.43 | Lift: 1.15
Bundle: ['curd'] -> ['whole milk'] | Confidence: 0.53 | Lift: 1.15
Bundle: ['bottled water'] -> ['whole milk'] | Confidence: 0.53 | Lift: 1.15
Bundle: ['frankfurter'] -> ['rolls/buns'] | Confidence: 0.40 | Lift: 1.15
Bundle: ['bottled beer'] -> ['other vegetables'] | Confidence: 0.43 | Lift: 1.15
Bundle: ['tropical fruit'] -> ['yogurt'] | Confidence: 0.32 | Lift: 1.14
Bundle: ['sausage'] -> ['rolls/buns'] | Confidence: 0.40 | Lift: 1.14
Bundle: ['rolls/buns', 'other vegetables'] -> ['soda'] | Confidence: 0.36 | Lift: 1.14
Bundle: ['butter'] -> ['whole milk'] | Confidence: 0.52 | Lift: 1.14
Bundle: ['bottled water'] -> ['soda'] | Confidence: 0.36 | Lift: 1.14
Bundle: ['bottled beer'] -> ['rolls/buns'] | Confidence: 0.40 | Lift: 1.14
Bundle: ['margarine'] -> ['other vegetables'] | Confidence: 0.43 | Lift: 1.14
Bundle: ['pastry'] -> ['soda'] | Confidence: 0.36 | Lift: 1.13
Bundle: ['sausage'] -> ['whole milk'] | Confidence: 0.52 | Lift: 1.13
Bundle: ['curd'] -> ['other vegetables'] | Confidence: 0.43 | Lift: 1.13
Bundle: ['pip fruit'] -> ['soda'] | Confidence: 0.35 | Lift: 1.13
Bundle: ['domestic eggs'] -> ['rolls/buns'] | Confidence: 0.39 | Lift: 1.13
Bundle: ['newspapers'] -> ['whole milk'] | Confidence: 0.52 | Lift: 1.13
Bundle: ['other vegetables'] -> ['yogurt'] | Confidence: 0.32 | Lift: 1.13
Bundle: ['yogurt'] -> ['other vegetables'] | Confidence: 0.43 | Lift: 1.13
Bundle: ['beef'] -> ['other vegetables'] | Confidence: 0.42 | Lift: 1.13
Bundle: ['pip fruit'] -> ['rolls/buns'] | Confidence: 0.39 | Lift: 1.13
Bundle: ['root vegetables'] -> ['rolls/buns'] | Confidence: 0.39 | Lift: 1.13
Bundle: ['pip fruit'] -> ['other vegetables'] | Confidence: 0.42 | Lift: 1.13
Bundle: ['whipped/sour cream'] -> ['whole milk'] | Confidence: 0.52 | Lift: 1.13
Bundle: ['rolls/buns'] -> ['yogurt'] | Confidence: 0.32 | Lift: 1.13
Bundle: ['yogurt'] -> ['rolls/buns'] | Confidence: 0.39 | Lift: 1.13
Bundle: ['root vegetables'] -> ['soda'] | Confidence: 0.35 | Lift: 1.12
Bundle: ['brown bread'] -> ['rolls/buns'] | Confidence: 0.39 | Lift: 1.12
Bundle: ['citrus fruit'] -> ['soda'] | Confidence: 0.35 | Lift: 1.12
Bundle: ['brown bread'] -> ['whole milk'] | Confidence: 0.51 | Lift: 1.12
Bundle: ['pastry'] -> ['rolls/buns'] | Confidence: 0.39 | Lift: 1.12
Bundle: ['pastry'] -> ['whole milk'] | Confidence: 0.51 | Lift: 1.12
Bundle: ['fruit/vegetable juice'] -> ['other vegetables'] | Confidence: 0.42 | Lift: 1.12
Bundle: ['tropical fruit'] -> ['soda'] | Confidence: 0.35 | Lift: 1.12
Bundle: ['pork'] -> ['other vegetables'] | Confidence: 0.42 | Lift: 1.12
Bundle: ['rolls/buns'] -> ['whole milk'] | Confidence: 0.51 | Lift: 1.11
Bundle: ['whole milk'] -> ['rolls/buns'] | Confidence: 0.39 | Lift: 1.11
Bundle: ['other vegetables'] -> ['rolls/buns'] | Confidence: 0.39 | Lift: 1.11
Bundle: ['rolls/buns'] -> ['other vegetables'] | Confidence: 0.42 | Lift: 1.11
Bundle: ['pip fruit'] -> ['whole milk'] | Confidence: 0.51 | Lift: 1.11
Bundle: ['margarine'] -> ['whole milk'] | Confidence: 0.51 | Lift: 1.11
Bundle: ['citrus fruit'] -> ['yogurt'] | Confidence: 0.31 | Lift: 1.11
Bundle: ['citrus fruit'] -> ['other vegetables'] | Confidence: 0.42 | Lift: 1.11
Bundle: ['other vegetables'] -> ['whole milk'] | Confidence: 0.51 | Lift: 1.11
Bundle: ['whole milk'] -> ['other vegetables'] | Confidence: 0.42 | Lift: 1.11
Bundle: ['canned beer'] -> ['yogurt'] | Confidence: 0.31 | Lift: 1.11
Bundle: ['bottled beer'] -> ['soda'] | Confidence: 0.35 | Lift: 1.11
Bundle: ['citrus fruit'] -> ['rolls/buns'] | Confidence: 0.39 | Lift: 1.11
Bundle: ['pork'] -> ['whole milk'] | Confidence: 0.51 | Lift: 1.10
Bundle: ['yogurt'] -> ['soda'] | Confidence: 0.34 | Lift: 1.10
Bundle: ['soda'] -> ['yogurt'] | Confidence: 0.31 | Lift: 1.10
Bundle: ['bottled water'] -> ['yogurt'] | Confidence: 0.31 | Lift: 1.10
Bundle: ['root vegetables'] -> ['yogurt'] | Confidence: 0.31 | Lift: 1.10
Bundle: ['soda'] -> ['rolls/buns'] | Confidence: 0.38 | Lift: 1.09
Bundle: ['rolls/buns'] -> ['soda'] | Confidence: 0.34 | Lift: 1.09
Bundle: ['fruit/vegetable juice'] -> ['whole milk'] | Confidence: 0.50 | Lift: 1.09
Bundle: ['tropical fruit'] -> ['whole milk'] | Confidence: 0.50 | Lift: 1.09
Bundle: ['citrus fruit'] -> ['whole milk'] | Confidence: 0.50 | Lift: 1.09
Bundle: ['chicken'] -> ['whole milk'] | Confidence: 0.50 | Lift: 1.09
Bundle: ['domestic eggs'] -> ['other vegetables'] | Confidence: 0.41 | Lift: 1.08
Bundle: ['root vegetables'] -> ['other vegetables'] | Confidence: 0.41 | Lift: 1.08
Bundle: ['whipped/sour cream'] -> ['rolls/buns'] | Confidence: 0.38 | Lift: 1.08
Bundle: ['canned beer'] -> ['other vegetables'] | Confidence: 0.41 | Lift: 1.08
Bundle: ['tropical fruit'] -> ['rolls/buns'] | Confidence: 0.38 | Lift: 1.08
Bundle: ['frankfurter'] -> ['whole milk'] | Confidence: 0.49 | Lift: 1.08
Bundle: ['root vegetables'] -> ['whole milk'] | Confidence: 0.49 | Lift: 1.07
Bundle: ['pastry'] -> ['other vegetables'] | Confidence: 0.40 | Lift: 1.07
Bundle: ['bottled water'] -> ['rolls/buns'] | Confidence: 0.37 | Lift: 1.06
Bundle: ['canned beer'] -> ['soda'] | Confidence: 0.33 | Lift: 1.06
Bundle: ['soda'] -> ['whole milk'] | Confidence: 0.48 | Lift: 1.05
Bundle: ['whole milk'] -> ['soda'] | Confidence: 0.33 | Lift: 1.05
Bundle: ['other vegetables'] -> ['soda'] | Confidence: 0.33 | Lift: 1.05
Bundle: ['soda'] -> ['other vegetables'] | Confidence: 0.40 | Lift: 1.05
Bundle: ['coffee'] -> ['whole milk'] | Confidence: 0.48 | Lift: 1.05
Bundle: ['tropical fruit'] -> ['other vegetables'] | Confidence: 0.39 | Lift: 1.04
Bundle: ['newspapers'] -> ['other vegetables'] | Confidence: 0.37 | Lift: 0.98

In [22]:
rules = rules.sort_values(by="confidence", ascending=False)

In [23]:
print(rules.head(10))

                            antecedents   consequents  antecedent support  \
98    (other vegetables, bottled water)  (whole milk)            0.093894
55           (yogurt, other vegetables)  (whole milk)            0.120318
76                 (rolls/buns, yogurt)  (whole milk)            0.111339
39       (rolls/buns, other vegetables)  (whole milk)            0.146742
108                      (soda, yogurt)  (whole milk)            0.097486
62             (soda, other vegetables)  (whole milk)            0.124166
126  (other vegetables, tropical fruit)  (whole milk)            0.091329
78                   (soda, rolls/buns)  (whole milk)            0.119805
28                      (shopping bags)  (whole milk)            0.168291
128         (sausage, other vegetables)  (whole milk)            0.092868

     consequent support   support  confidence      lift  representativity  \
98             0.458184  0.056183    0.598361  1.305941               1.0
55             0.458184  0.071832    0.597015  1.303003               1.0
76             0.458184  0.065931    0.592166  1.292420               1.0
39             0.458184  0.082093    0.559441  1.220996               1.0
108            0.458184  0.054387    0.557895  1.217622               1.0
62             0.458184  0.069266    0.557851  1.217528               1.0
126            0.458184  0.050539    0.553371  1.207749               1.0
78             0.458184  0.065162    0.543897  1.187072               1.0
28             0.458184  0.091329    0.542683  1.184422               1.0
128            0.458184  0.050282    0.541436  1.181702               1.0

     leverage  conviction  zhangs_metric   jaccard  certainty  kulczynski
98   0.013162    1.349012       0.258544  0.113295   0.258717    0.360491
55   0.016704    1.344507       0.264348  0.141772   0.256233    0.376895
76   0.014917    1.328521       0.254605  0.130922   0.247283    0.368031
39   0.014859    1.229837       0.212124  0.157017   0.186884    0.369306
108  0.009720    1.225537       0.198033  0.108495   0.184031    0.338298
62   0.012375    1.225416       0.203992  0.135000   0.183951    0.354514
126  0.008693    1.213123       0.189302  0.101285   0.175681    0.331837
78   0.010269    1.187926       0.179041  0.127064   0.158197    0.343057
28   0.014220    1.184772       0.187213  0.170662   0.155956    0.371006
128  0.007732    1.181551       0.169504  0.100410   0.153655    0.325589